**Classifying The IRIS species USING RANDOM FOREST**

In [1]:
from sklearn.datasets import load_iris

In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd
import numpy as np

np.random.seed(0)
iris = load_iris()
    
df= pd.DataFrame(iris.data, columns= iris.feature_names)

In [6]:
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [8]:
df['is_train']=np.random.uniform(0,1,len(df))<= .75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [9]:
train, test = df[df['is_train']==True],df[df['is_train']==False]
print('No. of observation in the training data :- ',len(train))
print('No. of observation in the testing data: ',len(test))

No. of observation in the training data :-  118
No. of observation in the testing data:  32


In [10]:
features = df.columns[:4]
print(features)
y = pd.factorize(train['species'])[0]
print(y)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2]


In [12]:

clf = RandomForestClassifier(n_jobs=2,random_state=0)

clf.fit(train[features],y)


RandomForestClassifier(n_jobs=2, random_state=0)

In [13]:
clf.predict(test[features])
clf.predict_proba(test[features])[10:20]
pre = iris.target_names[clf.predict(test[features])]

pre[0:35]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')

In [14]:
test['species'].head()
pd.crosstab(test['species'],pre,rownames=['Actual Species'], colnames= ['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [17]:
pre = iris.target_names[clf.predict([[5.0,3.6,1.4,2.0],[5.0,3.6,1.4,2.0]])]
pre


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['setosa', 'setosa'], dtype='<U10')

In [19]:
# Evaluate the model's performance
y_pred = clf.predict(train[features])
accuracy = accuracy_score(y, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 1.00


In [20]:
cm = confusion_matrix(y, y_pred)
print(f'Confusion matrix: \n{cm}')

Confusion matrix: 
[[37  0  0]
 [ 0 43  0]
 [ 0  0 38]]
